# Generated by Django 4.2.7 on 2025-08-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_canceled_at_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('OUT_FOR_DELIVERY', 'On its way'), ('DELIVERED', 'Delivered'), ('CANCELED_STORE', 'Canceled (Store pays)'), ('CANCELED_CLIENT', 'Canceled (Client pays)')], db_index=True, default='PENDING', max_length=32),
        ),
    ]
