# Generated by Django 4.2.7 on 2025-08-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='out_for_delivery_at',
            new_name='on_the_way_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='effects_applied',
            new_name='stock_deducted',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ON_THE_WAY', 'On the way'), ('DELIVERED', 'Delivered'), ('CANCELLED_BY_CLIENT', 'Cancelled by client'), ('CANCELLED_BY_OWNER', 'Cancelled by owner')], db_index=True, default='PENDING', max_length=32),
        ),
    ]
