# Generated by Django 4.2.7 on 2025-08-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_orders_orde_order_s_33197f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_s_33197f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_d_d71205_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_wilaya_56e64f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_s_1f0471_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='costumer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='costumer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('OnTheWay', 'On the Way'), ('Delivered', 'Delivered'), ('ReturnedByClient', 'Returned by Client'), ('ReturnedByOwner', 'Returned by Owner'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
