# Generated by Django 4.2.7 on 2025-08-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_orders_orde_order_s_33197f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Home', 'Home Delivery'), ('Bureau', 'Bureau Delivery')], default='Home', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.CharField(default='medea', max_length=100),
            preserve_default=False,
        ),
    ]
